In [1]:
import os
import re
import numpy as np
from tqdm import tqdm

Label the data -1 for interictal and 1 for preictal. 

In [2]:
root = '../feature_extraction/'
interictal_dirname = 'chb01_interictal_features'
preictal_dirname = 'chb01_preictal_features'

In [3]:
regex = re.compile('^chb\d{2}_\d{2}.npy$')
interictal_test_files = [x for x in os.listdir(root + interictal_dirname) if regex.search(x)]
interictal_test_files = sorted(interictal_test_files)

In [4]:
interictal_train_file = os.listdir(root + interictal_dirname)[0]

In [5]:
regex = re.compile('^chb\d{2}_preictal_\d.npy')
preictal_files = [x for x in os.listdir(root + preictal_dirname) if regex.search(x)]
preictal_files = sorted(preictal_files)

In [7]:
preictal_X_list = []
for i in tqdm(range(len(preictal_files))):
    data = np.load(root + preictal_files[i])
    preictal_X_list.append(data)

100%|██████████| 6/6 [00:00<00:00, 685.25it/s]


In [9]:
preictal_target_l = np.ones(len(preictal_X_list))
preictal_target_l

array([1., 1., 1., 1., 1., 1.])

In [12]:
interictal_X_test_list = []
for i in tqdm(range(len(interictal_test_files))):
    data = np.load(root + interictal_dirname + '/' + interictal_test_files[i])
    interictal_X_test_list.append(data)

100%|██████████| 35/35 [00:00<00:00, 310.43it/s]


In [13]:
interictal_target_l = -1 * np.ones(len(interictal_X_test_list))
interictal_target_l

array([-1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1., -1.,
       -1., -1., -1., -1., -1., -1., -1., -1., -1.])

In [24]:
np.load(root + interictal_dirname + '/' + interictal_train_file)[:1377].shape

(1377, 23, 2)

For training class -1, input will be a length 1377 vector with another target vector of length 1377.

In [22]:
print(np.load(root + preictal_dirname + '/' + preictal_files[0]).shape)
print(np.load(root + preictal_dirname + '/' + preictal_files[1]).shape)
print(np.load(root + preictal_dirname + '/' + preictal_files[2]).shape)

(459, 23, 2)
(459, 23, 2)
(459, 23, 2)


For training class 1, input will be 3 vectors of length 459 with another target vector of length 3x459=1377.

In [35]:
preictal_X = np.empty((459,23,2))
preictals = []
for i in range(3):
    fpath = root + preictal_dirname + '/' + preictal_files[i]
    data = np.load(fpath)
    preictals.append(data)
preictal_arr = np.array(preictals)
print(preictal_arr.shape)
preictal_arr = np.reshape(preictal_arr, (3*459, 23, 2))
print(preictal_arr.shape)

(3, 459, 23, 2)
(1377, 23, 2)


In [36]:
interictal_arr = np.load(root + interictal_dirname + '/' + interictal_train_file)[:1377]
interictal_arr.shape

(1377, 23, 2)

In [37]:
# save
fpath = './interictal_train.npy'
np.save(fpath, interictal_arr)

fpath = './preictal_train.npy'
np.save(fpath, preictal_arr)