In [1]:
import os
import re
import numpy as np

Label the data -1 for interictal and 1 for preictal. 

In [2]:
root = '../feature_extraction/'
interictal_dirname = 'chb01_interictal_features'
preictal_dirname = 'chb01_preictal_features'

In [3]:
regex = re.compile('^chb\d{2}_\d{2}.npy$')
interictal_test_files = [x for x in os.listdir(root + interictal_dirname) if regex.search(x)]
interictal_test_files = sorted(interictal_test_files)

In [4]:
regex = re.compile('^chb\d{2}_preictal_\d.npy')
preictal_files = [x for x in os.listdir(root + preictal_dirname) if regex.search(x)]
preictal_files = sorted(preictal_files)

In [5]:
interictal_train_file = os.listdir(root + interictal_dirname)[0]
interictal_train_file

'chb01_interictal_1.npy'

For training class -1, input will be a length 1377 vector with another target vector of length 1377.

In [6]:
interictal_arr = np.load(root + interictal_dirname + '/' + interictal_train_file)[:1377]
interictal_arr.shape

(1377, 23, 2)

In [7]:
print(np.load(root + preictal_dirname + '/' + preictal_files[0]).shape)
print(np.load(root + preictal_dirname + '/' + preictal_files[1]).shape)
print(np.load(root + preictal_dirname + '/' + preictal_files[2]).shape)

(459, 23, 2)
(459, 23, 2)
(459, 23, 2)


In [8]:
# save
fpath = './interictal_train.npy'
np.save(fpath, interictal_arr)

For training class 1, input will be 3 vectors of length 459 with another target vector of length 3x459=1377.

In [9]:
preictals = []
for i in range(3):
    fpath = root + preictal_dirname + '/' + preictal_files[i]
    data = np.load(fpath)
    preictals.append(data)
preictal_arr = np.array(preictals)
print(preictal_arr.shape)
preictal_arr = np.reshape(preictal_arr, (3*459, 23, 2))
print(preictal_arr.shape)

(3, 459, 23, 2)
(1377, 23, 2)


In [10]:
# save
fpath = './preictal_train.npy'
np.save(fpath, preictal_arr)

For test class -1, input vector will be of length 33x1377=45441.

In [11]:
# interictal test segment
interictals = []
for i in range(len(interictal_test_files)):
    fpath = root + interictal_dirname + '/' + interictal_test_files[i]
    data = np.load(fpath)[:1377]
    if data.shape[0] == 1377:
        interictals.append(data)
    else:
        print(data.shape)
    
interictal_arr = np.array(interictals)
print(interictal_arr.shape)
interictal_arr = np.reshape(interictal_arr, (33*1377, 23, 2))
print(interictal_arr.shape)

(1362, 23, 2)
(306, 23, 2)
(33, 1377, 23, 2)
(45441, 23, 2)


In [12]:
# save
fpath = './interictal_test.npy'
np.save(fpath, interictal_arr)

For test class 1, input vector will be of length 3x459=1377.

In [13]:
len(preictal_files)-3

3

In [14]:
preictals = []
for i in range(3, len(preictal_files)):
    fpath = root + preictal_dirname + '/' + preictal_files[i]
    data = np.load(fpath)
    preictals.append(data)
preictal_arr = np.array(preictals)
print(preictal_arr.shape)
preictal_arr = np.reshape(preictal_arr, (3*459, 23, 2))
print(preictal_arr.shape)

(3, 459, 23, 2)
(1377, 23, 2)


In [15]:
fpath = './preictal_test.npy'
np.save(fpath, preictal_arr)